### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by BigDeepBlue** [xczdenis/Auth_sprint_1#10]
Отлично 🔥
1. Давайте трейсер занесем под `if settings.enable_tracer`, чтобы была возможность его отключить в тех же тестах
2. Вот [эти параметры](https://github.com/xczdenis/Auth_sprint_1/blob/a9fdd6c07c1511a0a39f1eb465a41d5aa280965b/src/app/oauth2.py#L52) отправьте в настройки и  переменные окружения. Они вряд ли будут меняться часто, но все же это возможно.
3. Лишняя [строка](https://github.com/xczdenis/Auth_sprint_1/blob/a9fdd6c07c1511a0a39f1eb465a41d5aa280965b/src/app/utils.py#L21). Эта переменная переопределяется в любом случае.
4. Имена провайдеров (google, yandex и т.д.) лучше поместить в enum. Работа с литералами - всегда не очень хорошая практика. Далее с развитием проекта может возникнуть необходимость их использовать в коде. Работа с enum, как минимум, избавит нас от опасности опечатки.
5. В продолжение п.4 [тут](https://github.com/xczdenis/Auth_sprint_1/blob/a9fdd6c07c1511a0a39f1eb465a41d5aa280965b/src/app/api/v1/oauth/routes.py#L25) можно будет проверять, что в запросе пришло валидное имя провайдера.
6. [Лишний](https://github.com/xczdenis/Auth_sprint_1/blob/a9fdd6c07c1511a0a39f1eb465a41d5aa280965b/src/app/api/v1/oauth/routes.py#L24) else. https://pheanex.github.io/pylint/
7. Класс [Settings](https://github.com/xczdenis/Auth_sprint_1/blob/a9fdd6c07c1511a0a39f1eb465a41d5aa280965b/src/config.py#L30) можно немного доработать. Сейчас поля в нем зачем-то именованы как константы, что не совсем по pep8. Можно запросто привести их в нижний регистр и все будет работать как и раньше. Так как маппер BaseSettings регистронезависимый.

**Comment by xczdenis** [comment]
Ссылка на PR - PR #14 

По п.4 для имен провайдеров вместо enum.Enum я использую dataclass с параметрами `slots=True, frozen=True` т.к. он меньше весит и им удобнее опльзоваться. Поскольку работа идет со строковыми литералами, используя enum мне пришлось бы писать `OAuthProviders.yandex.value` или `OAuthProviders.yandex.name`, но я не хочу думать о том, в каком месте мне  нужен `.name`, а в каком `.value`
По п.7 я использую настройки в верхнем регистре потому что эти настройки являются [конфигом flask приложения](https://github.com/xczdenis/Auth_sprint_1/blob/main/src/app/__init__.py#L19). У flask приложения есть такие настройки как `SECRET_KEY`, поэтому и в `settings` я использую `SECRET_KEY`, а не `secret_key` - для единообразия.

**Comment by BigDeepBlue** [comment]
LGTM
